### PR TITLE
Bug fix for return expr statements

### PR DESCRIPTION
**Pull request by Yuepeng-Wang**
Fix Issue #17

### CODE REVIEW

**Comment by shuvendu-lahiri** [comment]
Can you please add a regression test that is fixed by this change?

**Comment by Yuepeng-Wang** [comment]
The regression test is added in e5b9a7a

**Comment by shuvendu-lahiri** [comment]
Can you pull from master and resolve the conflict on records.txt?

Also, how difficult is it to generalize this fix to the case of return tuples?

**Comment by Yuepeng-Wang** [comment]
The conflict is resolved now.
The tuple expression is not well supported for the time being. To generalize this fix to return tuple expressions would involve some other changes, e.g. tuple assignment, handling mixture of named and unnamed variables, etc. I think it's probably better to have a separate PR that systematically addresses issues about tuples.

**Comment by shuvendu-lahiri** [comment]
Can you please create a new issues for returns with tuples? So that we can at least close the current issue? Then I will merge.

**Comment by Yuepeng-Wang** [comment]
The new issue is created. #25

**Pull request merged**
