### PR TITLE
Supporting single modifier

### PR DESCRIPTION
**Pull request by rongpan**
multiple modifiers/modifier from inheritance not implemented yet

### CODE REVIEW

**Comment by rongpan** [comment]
Sure, we can talk about these changes. Is it Monday at 6pm PST? I can do both PST/CST.

1. Currently, whether the modifier has locals is not checked. Let me add.
2. If a function f has a modifier, and f.body ends in a return, a modifierPostLude is injected.
3. If there is multiple modifiers, we will have an assertion failure.

**Comment by rongpan** [comment]
Let me fix an error and pass the regression for multiple returns

**Comment by rongpan** [comment]
done

**Comment by shuvendu-lahiri** [comment]
Addresses #2 for the case of a modifier with no arguments and no local variables inside a modifier.

**Pull request merged**
